import { useState } from 'react'

function Settings() {
  const [settings, setSettings] = useState({
    platformName: 'Smart Cargo',
    supportEmail: 'support@smartcargo.com',
    currency: 'USD',
    language: 'English',
    emailNotifications: true,
    shipmentNotifications: true,
    paymentNotifications: true,
    documentNotifications: true,
  })

  const [saved, setSaved] = useState(false)

  const handleChange = (field, value) => {
    setSettings({
      ...settings,
      [field]: value,
    })

    setSaved(false)
  }

  const handleSave = () => {
    setSaved(true)

    setTimeout(() => {
      setSaved(false)
    }, 3000)
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-800">
          Admin Settings
        </h1>

        <p className="mt-2 text-slate-500">
          Manage platform preferences and administrator settings.
        </p>
      </div>

      {/* Platform Settings */}
      <div className="mb-6 rounded-xl bg-white p-6 shadow-sm">
        <h2 className="text-xl font-semibold text-slate-800">
          Platform Settings
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Configure the basic settings of the Smart Cargo platform.
        </p>

        <div className="mt-6 grid gap-5 md:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Platform Name
            </label>

            <input
              type="text"
              value={settings.platformName}
              onChange={(e) =>
                handleChange('platformName', e.target.value)
              }
              className="w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Support Email
            </label>

            <input
              type="email"
              value={settings.supportEmail}
              onChange={(e) =>
                handleChange('supportEmail', e.target.value)
              }
              className="w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Default Currency
            </label>

            <select
              value={settings.currency}
              onChange={(e) =>
                handleChange('currency', e.target.value)
              }
              className="w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500"
            >
              <option>USD</option>
              <option>INR</option>
              <option>EUR</option>
              <option>GBP</option>
            </select>
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Default Language
            </label>

            <select
              value={settings.language}
              onChange={(e) =>
                handleChange('language', e.target.value)
              }
              className="w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500"
            >
              <option>English</option>
              <option>Hindi</option>
            </select>
          </div>
        </div>
      </div>

      {/* Notification Settings */}
      <div className="mb-6 rounded-xl bg-white p-6 shadow-sm">
        <h2 className="text-xl font-semibold text-slate-800">
          Notification Settings
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Control notifications generated by the platform.
        </p>

        <div className="mt-6 space-y-5">
          <label className="flex items-center justify-between gap-4">
            <div>
              <p className="font-medium text-slate-800">
                Email Notifications
              </p>
              <p className="text-sm text-slate-500">
                Send important platform notifications through email.
              </p>
            </div>

            <input
              type="checkbox"
              checked={settings.emailNotifications}
              onChange={(e) =>
                handleChange(
                  'emailNotifications',
                  e.target.checked
                )
              }
              className="h-5 w-5"
            />
          </label>

          <label className="flex items-center justify-between gap-4">
            <div>
              <p className="font-medium text-slate-800">
                Shipment Updates
              </p>
              <p className="text-sm text-slate-500">
                Notify users when shipment status changes.
              </p>
            </div>

            <input
              type="checkbox"
              checked={settings.shipmentNotifications}
              onChange={(e) =>
                handleChange(
                  'shipmentNotifications',
                  e.target.checked
                )
              }
              className="h-5 w-5"
            />
          </label>

          <label className="flex items-center justify-between gap-4">
            <div>
              <p className="font-medium text-slate-800">
                Payment Notifications
              </p>
              <p className="text-sm text-slate-500">
                Notify users about payment status changes.
              </p>
            </div>

            <input
              type="checkbox"
              checked={settings.paymentNotifications}
              onChange={(e) =>
                handleChange(
                  'paymentNotifications',
                  e.target.checked
                )
              }
              className="h-5 w-5"
            />
          </label>

          <label className="flex items-center justify-between gap-4">
            <div>
              <p className="font-medium text-slate-800">
                Document Notifications
              </p>
              <p className="text-sm text-slate-500">
                Notify users about document approval or rejection.
              </p>
            </div>

            <input
              type="checkbox"
              checked={settings.documentNotifications}
              onChange={(e) =>
                handleChange(
                  'documentNotifications',
                  e.target.checked
                )
              }
              className="h-5 w-5"
            />
          </label>
        </div>
      </div>

      {/* Security */}
      <div className="mb-6 rounded-xl bg-white p-6 shadow-sm">
        <h2 className="text-xl font-semibold text-slate-800">
          Security
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Manage administrator security settings.
        </p>

        <div className="mt-5">
          <button
            onClick={() => alert('Password change feature will be connected to the backend later.')}
            className="rounded-lg border border-slate-300 px-5 py-3 font-medium text-slate-700 hover:bg-slate-50"
          >
            Change Password
          </button>
        </div>
      </div>

      {/* Save */}
      <div className="flex items-center justify-end gap-4">
        {saved && (
          <p className="text-sm font-medium text-green-600">
            Settings saved successfully.
          </p>
        )}

        <button
          onClick={handleSave}
          className="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white hover:bg-blue-700"
        >
          Save Settings
        </button>
      </div>
    </div>
  )
}

export default Settings